### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by gazzat5** [nthnn/SIM900#2]
**Describe the bug**
Unable to use the library inside the loop

**Expected behaviour**
Expected to be able to initialize the library in the global scope or the setup scope and use it inside the loop scope. However it is not possible to initialize it inside the setup and use it in the loop scope or in the global scope and use it in the loop scope as it says the object variable is not available.

**Pictures/Screenshots**
"C:\Users\garreth.tinsley\OneDrive - Watkins Payne Partnership\Documents\Arduino\Sketches\lowvoltage_alarm_sms_sim900\lowvoltage_alarm_sms_sim900.ino: In function 'void loop()':
C:\Users\garreth.tinsley\OneDrive - Watkins Payne Partnership\Documents\Arduino\Sketches\lowvoltage_alarm_sms_sim900\lowvoltage_alarm_sms_sim900.ino:48:7: error: 'rtc' was not declared in this scope
   48 |   if((rtc.hour <23) && (rtc.hour > 7)){
      |       ^~~
C:\Users\garreth.tinsley\OneDrive - Watkins Payne Partnership\Documents\Arduino\Sketches\lowvoltage_alarm_sms_sim900\lowvoltage_alarm_sms_sim900.ino:52:7: error: 'sim900' was not declared in this scope
   52 |       sim900.sendSMS("+447905839047", "Allotment Battery lower than 20%, please check.");
      |       ^~~~~~

exit status 1

Compilation error: 'rtc' was not declared in this scope"

**Additional context**
[lowvoltage_alarm_sms_sim900.txt](https://github.com/user-attachments/files/15890048/lowvoltage_alarm_sms_sim900.txt)

I have attached my sketch

**Comment by nthnn** [comment]
Hello, @gazzat5 This is not a bug. The `rtc` variable in your code was declared inside your `setup()` function, hence, you are not able to use it inside the `loop()` function.

It should be something like:

```cpp
// ...
SIM900RTC rtc;

void setup() {
    // Your setup code here
}

void loop() {
    // Use the rtc variable here
}
```
